### ISSUE TITLE
Cannot test pull requests from live branch

### ISSUE THREAD

**Issue by ianychoi** [aspnet/Docs.ko-kr#10]
@songgun made pull requests from live branch: https://github.com/aspnet/Docs.ko-kr/pull/6 and https://github.com/aspnet/Docs.ko-kr/pull/7 but validation CI returns some errors. On the other hand, pull requests from master branch: https://github.com/aspnet/Docs.ko-kr/pull/8 and https://github.com/aspnet/Docs.ko-kr/pull/9 execute validation CI jobs.

In my opinion, current CI jobs do not support pull requests from live branch. I did a few pull requests on other Korean documentation repos: https://github.com/MicrosoftDocs/sql-docs.ko-kr/pull/2 and https://github.com/Azure/azure-docs-cli-python.ko-kr/pull/1 which are based from live branch. Would the CI jobs for the repository need to update?

By the way, the document https://msdn.microsoft.com/ko-kr/communitydocs/community/edit-docs-on-github-guide indicates `master` branch. Might be the branch moving from `master` to `live` for all Microsoft document projects?

**Comment by nokura** [comment]
Hello @ianychoi 
Regarding contribution guide for docs.microsoft.com, please refer to https://docs.microsoft.com/ko-kr/contribute/.

**Comment by nokura** [comment]
Regarding PR, will you try it as we fixed the issue. I would appreciate if you could confirm that PR is now working.

**Comment by ianychoi** [comment]
Sorry for my late check - Thanks a lot for resolving it! :)
